// <auto-generated />
namespace SalesManagement.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AdjustCliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdjustCliente));
        
        string IMigrationMetadata.Id
        {
            get { return "201811201415253_AdjustCliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
